// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/stats/domain/usecases/get_user_stats_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:games_app/core/error/failures.dart' as _i5;
import 'package:games_app/core/shared/enums.dart' as _i7;
import 'package:games_app/features/stats/domain/entities/stats_entity.dart'
    as _i6;
import 'package:games_app/features/stats/domain/repositories/stats_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StatsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsRepository extends _i1.Mock implements _i3.StatsRepository {
  MockStatsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.StatsEntity>>> getUserStats(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.StatsEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.StatsEntity>>(
                    this,
                    Invocation.method(#getUserStats, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.StatsEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.StatsEntity?>> getUserStatsByGameType(
    String? userId,
    _i7.GameType? gameType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatsByGameType, [userId, gameType]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.StatsEntity?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.StatsEntity?>(
                    this,
                    Invocation.method(#getUserStatsByGameType, [
                      userId,
                      gameType,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.StatsEntity?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AggregateStatsEntity>>
  getAggregateStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAggregateStats, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.AggregateStatsEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.AggregateStatsEntity>(
                    this,
                    Invocation.method(#getAggregateStats, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AggregateStatsEntity>>);
}
