// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/game/data/repositories/game_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:games_app/features/game/data/datasources/game_firestore_datasource.dart'
    as _i4;
import 'package:games_app/features/game/data/datasources/game_remote_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GameRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRemoteDataSource extends _i1.Mock
    implements _i2.GameRemoteDataSource {
  MockGameRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> startGame(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#startGame, [lobbyId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> makeMove({
    required String? gameId,
    required int? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#makeMove, [], {
              #gameId: gameId,
              #position: position,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> abandonGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#abandonGame, [gameId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [gameId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [GameFirestoreDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameFirestoreDataSource extends _i1.Mock
    implements _i4.GameFirestoreDataSource {
  MockGameFirestoreDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Map<String, dynamic>> watchGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#watchGame, [gameId]),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> getGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [gameId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}
