// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/lobby/domain/usecases/toggle_ready_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:games_app/core/error/failures.dart' as _i6;
import 'package:games_app/core/shared/enums.dart' as _i7;
import 'package:games_app/features/lobby/domain/entities/lobby_entity.dart'
    as _i5;
import 'package:games_app/features/lobby/domain/repositories/lobby_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LobbyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLobbyRepository extends _i1.Mock implements _i3.LobbyRepository {
  MockLobbyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.LobbyEntity>> watchAvailableLobbies() =>
      (super.noSuchMethod(
            Invocation.method(#watchAvailableLobbies, []),
            returnValue: _i4.Stream<List<_i5.LobbyEntity>>.empty(),
          )
          as _i4.Stream<List<_i5.LobbyEntity>>);

  @override
  _i4.Stream<_i5.LobbyEntity> watchLobby(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#watchLobby, [lobbyId]),
            returnValue: _i4.Stream<_i5.LobbyEntity>.empty(),
          )
          as _i4.Stream<_i5.LobbyEntity>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.LobbyEntity>> createLobby({
    required String? name,
    required _i7.GameType? gameType,
    required int? maxPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLobby, [], {
              #name: name,
              #gameType: gameType,
              #maxPlayers: maxPlayers,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.LobbyEntity>>.value(
                  _FakeEither_0<_i6.Failure, _i5.LobbyEntity>(
                    this,
                    Invocation.method(#createLobby, [], {
                      #name: name,
                      #gameType: gameType,
                      #maxPlayers: maxPlayers,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.LobbyEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> joinLobby(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#joinLobby, [lobbyId]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#joinLobby, [lobbyId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> leaveLobby(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveLobby, [lobbyId]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#leaveLobby, [lobbyId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> toggleReady(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleReady, [lobbyId]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#toggleReady, [lobbyId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> updateGameType(
    String? lobbyId,
    _i7.GameType? gameType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGameType, [lobbyId, gameType]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#updateGameType, [lobbyId, gameType]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.LobbyEntity>> getLobby(
    String? lobbyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLobby, [lobbyId]),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.LobbyEntity>>.value(
                  _FakeEither_0<_i6.Failure, _i5.LobbyEntity>(
                    this,
                    Invocation.method(#getLobby, [lobbyId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.LobbyEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.LobbyEntity?>> getCurrentUserLobby() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserLobby, []),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.LobbyEntity?>>.value(
                  _FakeEither_0<_i6.Failure, _i5.LobbyEntity?>(
                    this,
                    Invocation.method(#getCurrentUserLobby, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.LobbyEntity?>>);
}
