// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web; // Use web config for Linux desktop
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRhfaGy76IfjEqNMj_9YUeCyWg7j5uBC8',
    appId: '1:108175310206:web:2b59919367a4be93cf072f',
    messagingSenderId: '108175310206',
    projectId: 'games-app-a3501',
    authDomain: 'games-app-a3501.firebaseapp.com',
    storageBucket: 'games-app-a3501.firebasestorage.app',
    measurementId: 'G-D7K76MJ8F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDrQdxaGGWMc-zt_AdvX1WBu6JWo9sWig',
    appId: '1:108175310206:android:85467206926515b9cf072f',
    messagingSenderId: '108175310206',
    projectId: 'games-app-a3501',
    storageBucket: 'games-app-a3501.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyg8kQYb__2IVFru2lzBZwG9X3TOMF0bw',
    appId: '1:108175310206:ios:47ab7ab66d96e69dcf072f',
    messagingSenderId: '108175310206',
    projectId: 'games-app-a3501',
    storageBucket: 'games-app-a3501.firebasestorage.app',
    iosBundleId: 'com.example.gamesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyg8kQYb__2IVFru2lzBZwG9X3TOMF0bw',
    appId: '1:108175310206:ios:47ab7ab66d96e69dcf072f',
    messagingSenderId: '108175310206',
    projectId: 'games-app-a3501',
    storageBucket: 'games-app-a3501.firebasestorage.app',
    iosBundleId: 'com.example.gamesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRhfaGy76IfjEqNMj_9YUeCyWg7j5uBC8',
    appId: '1:108175310206:web:c00674111a73fd70cf072f',
    messagingSenderId: '108175310206',
    projectId: 'games-app-a3501',
    authDomain: 'games-app-a3501.firebaseapp.com',
    storageBucket: 'games-app-a3501.firebasestorage.app',
    measurementId: 'G-K0Q1J29RXJ',
  );
}
