// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/stats/presentation/cubit/stats_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:games_app/core/error/failures.dart' as _i6;
import 'package:games_app/core/shared/enums.dart' as _i10;
import 'package:games_app/features/stats/domain/entities/stats_entity.dart'
    as _i7;
import 'package:games_app/features/stats/domain/repositories/stats_repository.dart'
    as _i2;
import 'package:games_app/features/stats/domain/usecases/get_aggregate_stats_usecase.dart'
    as _i8;
import 'package:games_app/features/stats/domain/usecases/get_stats_by_game_type_usecase.dart'
    as _i9;
import 'package:games_app/features/stats/domain/usecases/get_user_stats_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStatsRepository_0 extends _i1.SmartFake
    implements _i2.StatsRepository {
  _FakeStatsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetUserStatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserStatsUseCase extends _i1.Mock
    implements _i4.GetUserStatsUseCase {
  MockGetUserStatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StatsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeStatsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.StatsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.StatsEntity>>> call(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i7.StatsEntity>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i7.StatsEntity>>(
                    this,
                    Invocation.method(#call, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.StatsEntity>>>);
}

/// A class which mocks [GetAggregateStatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAggregateStatsUseCase extends _i1.Mock
    implements _i8.GetAggregateStatsUseCase {
  MockGetAggregateStatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StatsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeStatsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.StatsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.AggregateStatsEntity>> call(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, _i7.AggregateStatsEntity>
                >.value(
                  _FakeEither_1<_i6.Failure, _i7.AggregateStatsEntity>(
                    this,
                    Invocation.method(#call, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.AggregateStatsEntity>>);
}

/// A class which mocks [GetStatsByGameTypeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStatsByGameTypeUseCase extends _i1.Mock
    implements _i9.GetStatsByGameTypeUseCase {
  MockGetStatsByGameTypeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StatsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeStatsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.StatsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.StatsEntity?>> call(
    String? userId,
    _i10.GameType? gameType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId, gameType]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.StatsEntity?>>.value(
                  _FakeEither_1<_i6.Failure, _i7.StatsEntity?>(
                    this,
                    Invocation.method(#call, [userId, gameType]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.StatsEntity?>>);
}
