// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/game/domain/usecases/start_game_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:games_app/core/error/failures.dart' as _i6;
import 'package:games_app/features/game/domain/entities/game_entity.dart'
    as _i5;
import 'package:games_app/features/game/domain/repositories/game_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i3.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.GameEntity> watchGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#watchGame, [gameId]),
            returnValue: _i4.Stream<_i5.GameEntity>.empty(),
          )
          as _i4.Stream<_i5.GameEntity>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.GameEntity>> startGame(
    String? lobbyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startGame, [lobbyId]),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.GameEntity>>.value(
                  _FakeEither_0<_i6.Failure, _i5.GameEntity>(
                    this,
                    Invocation.method(#startGame, [lobbyId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.GameEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> makeMove({
    required String? gameId,
    required int? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#makeMove, [], {
              #gameId: gameId,
              #position: position,
            }),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#makeMove, [], {
                  #gameId: gameId,
                  #position: position,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> abandonGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#abandonGame, [gameId]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#abandonGame, [gameId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.GameEntity>> getGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [gameId]),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.GameEntity>>.value(
                  _FakeEither_0<_i6.Failure, _i5.GameEntity>(
                    this,
                    Invocation.method(#getGame, [gameId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.GameEntity>>);
}
