// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/game/presentation/cubit/game_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:games_app/core/error/failures.dart' as _i8;
import 'package:games_app/features/game/domain/entities/game_entity.dart'
    as _i6;
import 'package:games_app/features/game/domain/repositories/game_repository.dart'
    as _i2;
import 'package:games_app/features/game/domain/usecases/abandon_game_usecase.dart'
    as _i9;
import 'package:games_app/features/game/domain/usecases/make_move_usecase.dart'
    as _i7;
import 'package:games_app/features/game/domain/usecases/watch_game_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGameRepository_0 extends _i1.SmartFake
    implements _i2.GameRepository {
  _FakeGameRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WatchGameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchGameUseCase extends _i1.Mock implements _i4.WatchGameUseCase {
  MockWatchGameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GameRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeGameRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.GameRepository);

  @override
  _i5.Stream<_i6.GameEntity> call(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [gameId]),
            returnValue: _i5.Stream<_i6.GameEntity>.empty(),
          )
          as _i5.Stream<_i6.GameEntity>);
}

/// A class which mocks [MakeMoveUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMakeMoveUseCase extends _i1.Mock implements _i7.MakeMoveUseCase {
  MockMakeMoveUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GameRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeGameRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.GameRepository);

  @override
  _i5.Future<_i3.Either<_i8.Failure, void>> call({
    required String? gameId,
    required int? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #gameId: gameId,
              #position: position,
            }),
            returnValue: _i5.Future<_i3.Either<_i8.Failure, void>>.value(
              _FakeEither_1<_i8.Failure, void>(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #position: position,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i8.Failure, void>>);
}

/// A class which mocks [AbandonGameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbandonGameUseCase extends _i1.Mock
    implements _i9.AbandonGameUseCase {
  MockAbandonGameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GameRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeGameRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.GameRepository);

  @override
  _i5.Future<_i3.Either<_i8.Failure, void>> call(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [gameId]),
            returnValue: _i5.Future<_i3.Either<_i8.Failure, void>>.value(
              _FakeEither_1<_i8.Failure, void>(
                this,
                Invocation.method(#call, [gameId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i8.Failure, void>>);
}
