// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/lobby/presentation/cubit/lobby_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:games_app/core/error/failures.dart' as _i8;
import 'package:games_app/core/shared/enums.dart' as _i9;
import 'package:games_app/features/lobby/domain/entities/lobby_entity.dart'
    as _i6;
import 'package:games_app/features/lobby/domain/repositories/lobby_repository.dart'
    as _i2;
import 'package:games_app/features/lobby/domain/usecases/create_lobby_usecase.dart'
    as _i7;
import 'package:games_app/features/lobby/domain/usecases/join_lobby_usecase.dart'
    as _i10;
import 'package:games_app/features/lobby/domain/usecases/watch_available_lobbies_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLobbyRepository_0 extends _i1.SmartFake
    implements _i2.LobbyRepository {
  _FakeLobbyRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WatchAvailableLobbiesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchAvailableLobbiesUseCase extends _i1.Mock
    implements _i4.WatchAvailableLobbiesUseCase {
  MockWatchAvailableLobbiesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LobbyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLobbyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LobbyRepository);

  @override
  _i5.Stream<List<_i6.LobbyEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Stream<List<_i6.LobbyEntity>>.empty(),
          )
          as _i5.Stream<List<_i6.LobbyEntity>>);
}

/// A class which mocks [CreateLobbyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateLobbyUseCase extends _i1.Mock
    implements _i7.CreateLobbyUseCase {
  MockCreateLobbyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LobbyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLobbyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LobbyRepository);

  @override
  _i5.Future<_i3.Either<_i8.Failure, _i6.LobbyEntity>> call({
    required String? name,
    required _i9.GameType? gameType,
    required int? maxPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #name: name,
              #gameType: gameType,
              #maxPlayers: maxPlayers,
            }),
            returnValue:
                _i5.Future<_i3.Either<_i8.Failure, _i6.LobbyEntity>>.value(
                  _FakeEither_1<_i8.Failure, _i6.LobbyEntity>(
                    this,
                    Invocation.method(#call, [], {
                      #name: name,
                      #gameType: gameType,
                      #maxPlayers: maxPlayers,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i8.Failure, _i6.LobbyEntity>>);
}

/// A class which mocks [JoinLobbyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockJoinLobbyUseCase extends _i1.Mock implements _i10.JoinLobbyUseCase {
  MockJoinLobbyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LobbyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLobbyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LobbyRepository);

  @override
  _i5.Future<_i3.Either<_i8.Failure, void>> call(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [lobbyId]),
            returnValue: _i5.Future<_i3.Either<_i8.Failure, void>>.value(
              _FakeEither_1<_i8.Failure, void>(
                this,
                Invocation.method(#call, [lobbyId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i8.Failure, void>>);
}
