// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/lobby/presentation/cubit/lobby_waiting_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:games_app/core/error/failures.dart' as _i9;
import 'package:games_app/core/shared/enums.dart' as _i12;
import 'package:games_app/features/game/domain/entities/game_entity.dart'
    as _i14;
import 'package:games_app/features/game/domain/repositories/game_repository.dart'
    as _i4;
import 'package:games_app/features/game/domain/usecases/start_game_usecase.dart'
    as _i13;
import 'package:games_app/features/lobby/domain/entities/lobby_entity.dart'
    as _i7;
import 'package:games_app/features/lobby/domain/repositories/lobby_repository.dart'
    as _i2;
import 'package:games_app/features/lobby/domain/usecases/leave_lobby_usecase.dart'
    as _i8;
import 'package:games_app/features/lobby/domain/usecases/toggle_ready_usecase.dart'
    as _i10;
import 'package:games_app/features/lobby/domain/usecases/update_game_type_usecase.dart'
    as _i11;
import 'package:games_app/features/lobby/domain/usecases/watch_lobby_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLobbyRepository_0 extends _i1.SmartFake
    implements _i2.LobbyRepository {
  _FakeLobbyRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameRepository_2 extends _i1.SmartFake
    implements _i4.GameRepository {
  _FakeGameRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WatchLobbyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchLobbyUseCase extends _i1.Mock implements _i5.WatchLobbyUseCase {
  MockWatchLobbyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LobbyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLobbyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LobbyRepository);

  @override
  _i6.Stream<_i7.LobbyEntity> call(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [lobbyId]),
            returnValue: _i6.Stream<_i7.LobbyEntity>.empty(),
          )
          as _i6.Stream<_i7.LobbyEntity>);
}

/// A class which mocks [LeaveLobbyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaveLobbyUseCase extends _i1.Mock implements _i8.LeaveLobbyUseCase {
  MockLeaveLobbyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LobbyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLobbyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LobbyRepository);

  @override
  _i6.Future<_i3.Either<_i9.Failure, void>> call(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [lobbyId]),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, void>>.value(
              _FakeEither_1<_i9.Failure, void>(
                this,
                Invocation.method(#call, [lobbyId]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, void>>);
}

/// A class which mocks [ToggleReadyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleReadyUseCase extends _i1.Mock
    implements _i10.ToggleReadyUseCase {
  MockToggleReadyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LobbyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLobbyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LobbyRepository);

  @override
  _i6.Future<_i3.Either<_i9.Failure, void>> call(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [lobbyId]),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, void>>.value(
              _FakeEither_1<_i9.Failure, void>(
                this,
                Invocation.method(#call, [lobbyId]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, void>>);
}

/// A class which mocks [UpdateGameTypeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateGameTypeUseCase extends _i1.Mock
    implements _i11.UpdateGameTypeUseCase {
  MockUpdateGameTypeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LobbyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLobbyRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LobbyRepository);

  @override
  _i6.Future<_i3.Either<_i9.Failure, void>> call(
    String? lobbyId,
    _i12.GameType? gameType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [lobbyId, gameType]),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, void>>.value(
              _FakeEither_1<_i9.Failure, void>(
                this,
                Invocation.method(#call, [lobbyId, gameType]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, void>>);
}

/// A class which mocks [StartGameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartGameUseCase extends _i1.Mock implements _i13.StartGameUseCase {
  MockStartGameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GameRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeGameRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.GameRepository);

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i14.GameEntity>> call(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [lobbyId]),
            returnValue:
                _i6.Future<_i3.Either<_i9.Failure, _i14.GameEntity>>.value(
                  _FakeEither_1<_i9.Failure, _i14.GameEntity>(
                    this,
                    Invocation.method(#call, [lobbyId]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i14.GameEntity>>);
}
