// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/auth/domain/usecases/sign_out_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:games_app/core/error/failures.dart' as _i5;
import 'package:games_app/features/auth/domain/entities/user_entity.dart'
    as _i6;
import 'package:games_app/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>
  signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserEntity>(
                    this,
                    Invocation.method(#signInWithEmailAndPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>
  signUpWithEmailAndPassword({
    required String? email,
    required String? password,
    required String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [], {
              #email: email,
              #password: password,
              #username: username,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserEntity>(
                    this,
                    Invocation.method(#signUpWithEmailAndPassword, [], {
                      #email: email,
                      #password: password,
                      #username: username,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserEntity?>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity?>>);

  @override
  _i4.Stream<_i6.UserEntity?> watchAuthState() =>
      (super.noSuchMethod(
            Invocation.method(#watchAuthState, []),
            returnValue: _i4.Stream<_i6.UserEntity?>.empty(),
          )
          as _i4.Stream<_i6.UserEntity?>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getIdToken({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [], {#forceRefresh: forceRefresh}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#getIdToken, [], {
                  #forceRefresh: forceRefresh,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>> updateUser({
    required String? id,
    String? username,
    String? displayName,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {
              #id: id,
              #username: username,
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserEntity>(
                    this,
                    Invocation.method(#updateUser, [], {
                      #id: id,
                      #username: username,
                      #displayName: displayName,
                      #photoURL: photoURL,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);
}
