// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/stats/data/repositories/stats_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:games_app/core/shared/enums.dart' as _i5;
import 'package:games_app/features/stats/data/datasources/stats_remote_datasource.dart'
    as _i3;
import 'package:games_app/features/stats/data/models/stats_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAggregateStatsModel_0 extends _i1.SmartFake
    implements _i2.AggregateStatsModel {
  _FakeAggregateStatsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StatsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsRemoteDataSource extends _i1.Mock
    implements _i3.StatsRemoteDataSource {
  MockStatsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.StatsModel>> getUserStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, [userId]),
            returnValue: _i4.Future<List<_i2.StatsModel>>.value(
              <_i2.StatsModel>[],
            ),
          )
          as _i4.Future<List<_i2.StatsModel>>);

  @override
  _i4.Future<_i2.StatsModel?> getUserStatsByGameType(
    String? userId,
    _i5.GameType? gameType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatsByGameType, [userId, gameType]),
            returnValue: _i4.Future<_i2.StatsModel?>.value(),
          )
          as _i4.Future<_i2.StatsModel?>);

  @override
  _i4.Future<_i2.AggregateStatsModel> getAggregateStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAggregateStats, [userId]),
            returnValue: _i4.Future<_i2.AggregateStatsModel>.value(
              _FakeAggregateStatsModel_0(
                this,
                Invocation.method(#getAggregateStats, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.AggregateStatsModel>);
}
