// Mocks generated by Mockito 5.4.6 from annotations
// in games_app/test/features/lobby/data/repositories/lobby_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:games_app/core/shared/enums.dart' as _i4;
import 'package:games_app/features/lobby/data/datasources/lobby_firestore_datasource.dart'
    as _i5;
import 'package:games_app/features/lobby/data/datasources/lobby_remote_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LobbyRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLobbyRemoteDataSource extends _i1.Mock
    implements _i2.LobbyRemoteDataSource {
  MockLobbyRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> createLobby({
    required String? name,
    required _i4.GameType? gameType,
    required int? maxPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLobby, [], {
              #name: name,
              #gameType: gameType,
              #maxPlayers: maxPlayers,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> joinLobby(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#joinLobby, [lobbyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> leaveLobby(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveLobby, [lobbyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleReady(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleReady, [lobbyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGameType(String? lobbyId, _i4.GameType? gameType) =>
      (super.noSuchMethod(
            Invocation.method(#updateGameType, [lobbyId, gameType]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getLobby(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#getLobby, [lobbyId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAvailableLobbies() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableLobbies, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getCurrentUserLobby() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserLobby, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}

/// A class which mocks [LobbyFirestoreDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLobbyFirestoreDataSource extends _i1.Mock
    implements _i5.LobbyFirestoreDataSource {
  MockLobbyFirestoreDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<Map<String, dynamic>>> watchAvailableLobbies() =>
      (super.noSuchMethod(
            Invocation.method(#watchAvailableLobbies, []),
            returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Stream<Map<String, dynamic>> watchLobby(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#watchLobby, [lobbyId]),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> getLobby(String? lobbyId) =>
      (super.noSuchMethod(
            Invocation.method(#getLobby, [lobbyId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}
